spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}

mysql:
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL}

amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}