server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

keycloak:
  realm: catalogo-admin
  host: http://localhost:8443

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3306

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456