server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  lifecycle:
    timeout-per-shutdown-phase: 500ms
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # É uma configuração em milliseconds. O ideal é manter baixo para que estoure timeout logo e não prenda as threads.
      max-lifetime: 600000 # Tempo máximo que uma conexão pode ficar aberta (10 min) - security.
      maximum-pool-size: 20 # Mantemos até no máx 20 conexões com o banco de dados. O ideal é manter baixo mesmo, pois é algo custoso para o banco gerenciar. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10 # minimo de threads que o pool pode diminuir quando existirem muitas conexoes ociosas
      pool-name: master # define o nome do pool de threads
  jpa:
    open-in-view: false # abre uma conexão (escopo trasacional) com BD desde o controller, fazendo tudo que é executado dentro do controller na mesma transação podendo afetar a performance da app
    show-sql: true
    hibernate:
      ddl-auto: none # atualiza o schema do banco automaticamente
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      # Para aumentar a performance ao máximo, desabilitamos o auto-commit e o open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
  rabbitmq:
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}

logging:
  level:
    ROOT: info
    com.fullcycle.catalogo: DEBUG

gcloud:
  credentials: ${GCLOUD_CREDENTIALS}
  project-id: ${GCLOUD_PROJECT_ID}
  storage:
    catalogo-videos:
      bucket: bucket
      connect-timeout: 1000
      read-timeout: 2000
      retry-max-attempts: 2
      retry-delay: 50
      retry-max-delay: 50
      retry-multiplier: 1.0

storage:
  catalogo-videos:
    filename-pattern: type-{type}
    location-pattern: videoId-{videoId}

amqp:
  admin:
    auto-create: false
  queues:
    video-created:
      exchange: videos.events
      routing-key: video.created
      queue: video.created.queue
    video-encoded:
      exchange: videos.events
      routing-key: video.encoded
      queue: video.encoded.queue