version: '3.8'

services:
  app:
    container_name: adm_videos_app
    build:
      context: ../../
      dockerfile: Dockerfile.sandbox
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true