name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'hotfix/**'
      - 'releases/**'
      - 'feat/**'
  workflow_dispatch:

env:
  IMAGE_NAME: gabrielmqsouza/catalogo-admin

jobs:
  # Job para execucão dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # configura os passos do job de teste
    steps:
      # 1 - Checkout do código fonte
      - uses: actions/checkout@v3
      # 2 - Configura a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        # passando parametros para a action
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3 - Executando os testes da aplicacao
      - name: Run application tests
        run: ./gradlew test

  # Job para buildar a aplicacao
  build:
    name: Build runner
    needs: tests # depende do job tests tem ter sucesso para iniciar a execucao
    runs-on: ubuntu-latest
    # configura os passos do job de build
    steps:
      # 1 - Checkout do código fonte
      - uses: actions/checkout@v3
      # 2 - Configura a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3 - valida se a existencia do gradle wrapper na maquina
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      # 4 - Realizar o build para gerar o artefato final
      - name: Application build
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test
      # 5 - Definir a variaveel branch name
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6 - Print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      # 7 - Log in DockerHub
      - name: Log in DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 8 - Build & Deploy da imagem
      - name: Build & push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}